service: tpoc

provider:
  name: aws
  stage: ${opt.stage, 'dev'}
  region: ap-southeast-1
  runtime: nodejs16.x
  environment:
    TRANSFER_QUEUE: ${sls:stage}-transfer-queue
    CHECK_TRANSFER_QUEUE: ${sls:stage}-check-transfer-queue
    DATABASE_URL: ${ssm:/aws/reference/secretsmanager/tpoc-secret/databaseUrl}
    ACCOUNT_PRIVATE_KEY: ${ssm:/aws/reference/secretsmanager/tpoc-secret/accountPrivateKey}
    INFURA_URL: ${ssm:/aws/reference/secretsmanager/tpoc-secret/infuraUrl}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:GetQueueAttributes
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:SendMessage
            - sqs:GetQueueUrl
          Resource: '*'
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource: 'arn:aws:secretsmanager:ap-southeast-1:960458344811:secret:tpoc-secret*'

custom:
  esbuild:
    target: es2019
    minify: true
    bundle: true

plugins:
  - serverless-esbuild

functions:
  getTransferById:
    handler: src/endpoints.getTransferById
    events:
      - http:
          method: GET
          path: transfers/{transferId}
  createTransfer:
    handler: src/endpoints.createTransfer
    events:
      - http:
          method: POST
          path: transfers
  processTransfer:
    handler: src/transfer.processTransfer
    # reservedConcurrency: 1
    events:
      - sqs:
          arn: !GetAtt ProcessTransferQueue.Arn
  checkTransfer:
    handler: src/transfer.checkTransfer
    # reservedConcurrency: 1
    events:
      - sqs:
          arn: !GetAtt CheckTransferQueue.Arn

resources:
  Resources:
    ProcessTransferQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.TRANSFER_QUEUE}
        VisibilityTimeout: 900
        MessageRetentionPeriod: 3600
    CheckTransferQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.CHECK_TRANSFER_QUEUE}
        VisibilityTimeout: 900
        MessageRetentionPeriod: 3600
